/*****************************************************************************
** Demo program to show how to output text to a drawmap in MAUI and         **
** wait for user input.                                                     **
******************************************************************************
** Copyright 1996 by Microware Systems Corporation                          **
** Reproduced Under License                                                 **
**                                                                          **
** This source code is the proprietary confidential property of             **
** Microware Systems Corporation, and is provided to licensee               **
** solely for documentation and educational purposes. Reproduction,         **
** publication, or distribution in any form to any party other than         **
** the licensee is strictly prohibited.                                     **
******************************************************************************
** Edition History:                                                         **
** #   Date     Comments                                          By        **
** --- -------- ------------------------------------------------- --------- **
**   1 03/15/96 creation                                          bat       **
*****************************************************************************/

/*
**	Definitions for Sun's raster image file format
*/

#ifndef _SUNRAST_H
#define _SUNRAST_H

#include <types.h>

typedef struct rasterfile {
	u_int32	ras_magic;					/* magic cookie for raster images */
		#define RAS_MAGIC	0x59a66a95		/* magic cookie definition */
	u_int32 ras_width;					/* image's width in pixels */
	u_int32 ras_height;					/* image's height in pixels */
	u_int32 ras_depth;					/* image's depth in pixels (1/8/24) */
	u_int32 ras_length;					/* byte length of image data */
	u_int32 ras_type;					/* type of data file */
		#define RT_OLD			0x0000		/* raw pixrect image (big-end) */
		#define RT_STANDARD		0x0001		/* raw pixrect image (big-end) */
		#define RT_BYTE_ENCODED	0x0002		/* run-length compression */
		#define RT_FORMAT_RGB	0x0003		/* XRGB/RGB format */
		#define RT_FORMAT_TIFF	0x0004		/* tiff format */
		#define RT_FORMAT_IFF	0x0005		/* iff (TAAC format) */
		#define RT_EXPERIMENTAL	0xffff		/* reserved for testing */
	u_int32 ras_maptype;				/* type of color-map */
		#define RMT_NONE		0x0000		/* ras_maplength = 0 */
		#define RMT_EQUAL_RGB	0x0001		/* red[ras_maplength/3]/g[]/b[] */
		#define RMT_RAW			0x0002		/* raw Sun colormap */
	u_int32 ras_maplength;				/* byte length of colormap data */
	/** color-map data (possibly empty) **/
	/** image data: pixels ordered in increasing lines **/
} rasterfile, *Rasterfile;

/* NOTES:
**  Each line of the image is rounded out to a multiple of 16 bits.
**   This corresponds to the rounding convention used by the memory pixrect
**   package (/usr/include/pixrect/memvar.h) of the SunWindows system.
**  The ras_encoding field (always set to 0 by Sun's supported software)
**   was renamed to ras_length in release 2.0.  As a result, rasterfiles
**   of type 0 generated by the old software claim to have 0 length; for
**   compatibility, code reading rasterfiles must be prepared to compute the
**   true length from the width, height, and depth fields.
*/


#endif /* _SUNRAST_H */
