# Makefile for all CBOOT BOOTLIB contents

-x
-b

MAKERS		= bootlib.make

MWOS		= ../../../../../..
MAKER		= ./makefile				# this file

include $(MWOS)/MAKETMPL/makeosk.tpl

$(MAKERS):
	$(MAKESUB) -f=$@


# end of file
